### ISSUE TITLE
Extend with support for InFocus IN76?

### ISSUE THREAD

**Issue by petterreinholdtsen** [fredrik-eriksson/kodi_projcontrol#1]
Hi.  Having my Kodi instance handle the project seem like a good idea.  I got a InFocus projector with a serial port interface, and the protocol is trivial and well documented.  Would you be willing to help me integrate support for it into this add-on?

A small python script talking to the projector is available from <URL: https://github.com/petterreinholdtsen/infocus-projector-control >.  As you can see there, it is fairly simple to talk to the projector.

I would love to turn the projector automatically off shortly after the screen saver kick in, to save the bulb.  Do you have any idea how to make that happen with Kodi?  It could even turn on the projector again when the screen saver is deactivated. :)

**Comment by fredrik-eriksson** [comment]
Hi, Thank you for showing interest!

Unfortunately I no longer use this myself, and have no setup to test it, but if you want to add support for your projector I can try to point you in the right direction :)

To add the new projector protocol you first need to implement a ProjectorInstance class in a new file lib/infocus.py in a similar way like lib/epson.py. The important method in the class is send_command() which is used by the plugin to send commands to the projector.

Then you need to update lib/commands.py in do_cmd() (and set_source() and get_available_sources() if you want to be able to switch input source). The serial settings are also hardcoded in this file, so if those settings does not work for your projector you may need to change them (This should really be configured in the vendor protocol files, but I guess I got lazy).

You also need to update resources/settings.xml to allow the projector to be configured in the kodi addon-settings.


To automatically turn the projector on and off with the screensaver you need to edit the ProjectorMonitor class in service.py. If I understand https://codedocs.xyz/xbmc/xbmc/group__python__monitor.html correctly you just need to implement a onScreensaverActivated() and onScreensaverDeactivated() method which basically just does lib.commands.do_cmd(lib.CMD_PWR_OFF) (and CMD_PWR_ON).

I think that's all you need if you want to add a new projector for this plugin. If you do implement it I would be happy to merge a pull request :)

**Comment by petterreinholdtsen** [comment]
Hi, and thank you for your swift reply. :)

After skimming your email, it seem to contain most of what I need to get
going.  It will take a while to digest.

I spoke with the people on #kodi (freenode), earlier today, and they
seemed interested in making he serial python module available from the
central repository.  It will make it easier to publish this module there
too.  I did not dare to ask for similar treatment for flask.

Btw, can you explain why you used a REST service and a separate process
for the projector control system?  Why not just connect to the serial
port whenever a command should be sent to the projector?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by fredrik-eriksson** [comment]
Actually, in reality the plugin does a new connection to the serial port whenever a command should be sent, so it doesn't hog the serial port. The real reasons it's implemented as a service is because I want to run media library updates in regular intervals while the projector is off (by implementing a xbmc.Monitor class), as well as to be able to run the REST server.

Originally I used this to solve two problems, and one of the problems was not really related to Kodi. The first problem was to update the media libraries when the media center was not in use (which I detected by checking if the projector was off). The second problem was to control the projector for home automation, for example start the projector and switch input to a game console. This used the REST API, and it was really out of convenience that these two functions was integrated to a single kodi plugin.

I guess there are three options to handle the REST server:
  1. Remove it
  2. Replace flask with something else
  3. Add flask to the plugin code base
  4. Make it optional and auto-detect if flask is available

I actually think 4. is the easiest one if we want to keep the functionality. I could look into that.

**Comment by fredrik-eriksson** [comment]
So, I think all that is left is to implement support for your projector protocol. I made the methods in command.py slightly more generic, so all you need to do is:

  1. implement lib/infocus.py with the methods get_valid_sources(), get_serial_options(), get_source_id() as well as the class ProjectorInstance with method send_command() - this should be fairly easy to do using epson.py for inspiration.
  2. InFocus should be added as allowed value for Manufacturer in resources/settings.xml and a new subsetting (infocus_model) should be added for your model.
  3. commands.py should import the new module and the methods _get_proj_module_() and _get_configured_model_() needs to be updated to return the correct module and module name.

I haven't really tested the changes, so if you find any bugs feel free to fix them or just let me know :)

**Comment by petterreinholdtsen** [comment]
I have tried to follow your instructions and implemented this.  I've tested it using dummy xbmc classes, and can confirm that the power on/off command work with my InFocus projector. Are you OK with this code?

**Comment by fredrik-eriksson** [comment]
Good job with the InFocus code, since it's merged now I'm closing this :)
