### ISSUE TITLE
Device Support Request

### ISSUE THREAD

**Issue by DJPlaya** [fredrik-eriksson/kodi_projcontrol#20]
This Protocol is Valid for the following (and maybe more) Devices of the Brand 3M:
Proved compatible: x62, x62w, x64, x64W 
There are many other Projectors from this Series, i allready contacted the Company to get Information on this.

You can find the Control Protocol here: https://www.projektoren-datenbank.com/pdf/3mx62-rs232c.pdf

Thanks for doing this <3

**Comment by fredrik-eriksson** [comment]
Hi, Thanks for the interest and sorry for the late reply. Unfortunately, since this looks like a binary protocol, I'm not confident enough to implement this without having a projector to test with, but if you have some python experience you could take a look at epson.py to get a hint on how to implement this. I'll gladly integrate it if it is implemented.

**Comment by DJPlaya** [comment]
Sadly ime also not that good in Programming. But if you want, i could give you remote Access to an Computer with a Serial Connection to a Projector from the Series

**Comment by fredrik-eriksson** [comment]
Thanks, but I don't think that's feasible. I'll leave this issue open in case someone else is up for the challenge.

**Comment by fredrik-eriksson** [comment]
I'm archiving this project as I have no need for it anymore and generally was not very active on it anyway. Feel free to continue development in a fork if you still find it useful.
