### ISSUE TITLE
Device Support Request - Epson Powerlite 820p

### ISSUE THREAD

**Issue by CapPow** [fredrik-eriksson/kodi_projcontrol#21]
@fredrik-eriksson, thanks for the add-on! I have an Epson Powerlite 820p connected over USB, would it be possible to add support for this device?

**Comment by fredrik-eriksson** [comment]
I don't think it's possible to control the projector over USB; I use pyserial to communicate with the projector, so I guess if the projector acts as a usb->serial converter you just have to figure out the serial path/name (like /dev/ttyUSB0 or COM3 or something similar). Otherwise you should get an usb->serial converter and connect the projector using the RS-323C-connector.

I found the manual for the projector here: https://www.projectorcentral.com/pdf/projector_manual_1747.pdf and it seems to use the same communication protocol as the TW3200 so I added support for it in the branch epson-820p, feel free to test it and let me know how it works.

**Comment by fredrik-eriksson** [comment]
Support for serial has been added, but USB is (at least currently) out of scope.
