### ISSUE TITLE
Device Support Request - Benq

### ISSUE THREAD

**Issue by wilkgr76** [fredrik-eriksson/kodi_projcontrol#23]
Hi! Many Benq projectors have an RS232 socket. The protocol for controlling it is [public on their website](https://business-display.benq.com/content/dam/bb/en/product/projector/corporate/lh770/quick-start-guide/lh770-rs232-control-guide-0-windows7-windows8-winxp.pdf).

I don't currently have time but I'm happy to give this a crack myself once I do have time (in about a month or so)

**Comment by fredrik-eriksson** [comment]
Hi, I took a quick look, and it looks like it should be simple enough to implement; however, since I have no benq-projector to test with I can't really implement this (the manual does not say exactly what the response is to read queries for example, and I have no means to test). I would gladly merge a PR with this though!

**Comment by wilkgr76** [comment]
My USB-to-serial adapter hasn't arrived yet unfortunately, so it might be longer than I anticipated to add this. I'll be sure to make a PR when I have though!

**Comment by ZippierOstrich1** [comment]
Hi, I got a BenQ projector and tried to implement this by looking at the examples provided (infocus.py and epson.py) and mesh them somehow together to a working code. I didn't get it to work as I am quite the beginner with programming (and git/github) and sometimes didn't really understand what the code was supposed to do. I made a PR nevertheless  if one or both of you got the time and nerve to look over it and maybe @wilkgr76 wants to work with that instead of starting from scratch. I'll sure try it again some time later. Thanks!

**Comment by wilkgr76** [comment]
I'd be happy to! My serial adapter hasn't arrived still 😦 but I'll still be happy to take a look and see if I can help out! (PR is #24 btw)

**Comment by ZippierOstrich1** [comment]
Got it working if you still want to take a look(#24). Corrections are always welcome

**Comment by wilkgr76** [comment]
Christ, I completely forgot about this. My adapter never ended up arriving and I ended up getting distracted haha.

**Comment by fredrik-eriksson** [comment]
Closed since merged in #24
